# Generated by Django 3.0.4 on 2020-03-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('date_Time_Start', models.DateTimeField()),
                ('date_Time_End', models.DateTimeField()),
            ],
        ),
    ]
